In [1]:
import pandas as pd

In [2]:
rain_data = pd.read_csv("all_data.csv", index_col=0)

In [3]:
rain_data.dtypes

date               object
time               object
station            object
value             float64
humidity          float64
temperature       float64
wind_direction    float64
wind_speed        float64
dtype: object

In [4]:
rain_data

,date,time,station,value,humidity,temperature,wind_direction,wind_speed
0,2023-02-03,00:05:00,S77,0.0,NaN,NaN,NaN,NaN
1,2023-02-03,00:10:00,S77,0.0,NaN,NaN,NaN,NaN
2,2023-02-03,00:15:00,S77,0.0,NaN,NaN,NaN,NaN
3,2023-02-03,00:20:00,S77,0.0,NaN,NaN,NaN,NaN
4,2023-02-03,00:25:00,S77,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
25797649,2020-06-09,23:35:00,S122,NaN,NaN,NaN,NaN,NaN
25797650,2020-06-09,23:40:00,S122,NaN,NaN,NaN,NaN,NaN
25797651,2020-06-09,23:45:00,S122,NaN,NaN,NaN,NaN,NaN
25797652,2020-06-09,23:50:00,S122,NaN,NaN,NaN,NaN,NaN
25797653,2020-06-09,23:55:00,S122,NaN,NaN,NaN,NaN,NaN

### Check the number of non NA values for the dataset, for each station

In [5]:
pd.set_option('display.max_rows', 90)

rain_data.groupby("station").count()

,date,time,value,humidity,temperature,wind_direction,wind_speed
station,,,,,,,
S07,317622,317622,96902,0,0,0,0
S08,317622,317622,316489,0,0,0,0
S100,321526,321526,313207,313224,313192,62090,62242
S102,321526,321526,30235,26149,28308,4992,5050
S104,321526,321526,306651,306005,306003,58984,59254
S105,317622,317622,2126,0,0,0,0
S106,321526,321526,298500,293516,293519,56517,56652
S107,321526,321526,313432,313821,313795,60142,60850
S108,321526,321526,296736,258179,296354,58309,58791
S109,321526,321526,303390,283231,303678,60075,60298
S11,317622,317622,186061,0,0,0,0
S111,321526,321526,309728,308918,308918,8347,8420
S112,317622,317622,309035,0,0,0,0
S113,317622,317622,317404,0,0,0,0
S114,317622,317622,310540,0,0,0,0
S115,321526,321526,306772,304532,304540,60820,60962
S116,321526,321526,307217,297712,305939,59945,60212
S117,321526,321526,99506,97362,101174,55866,56195
S118,317622,317622,312936,0,0,0,0
S119,317622,317622,307880,0,0,0,0
S120,317622,317622,316247,0,0,0,0
S121,321526,321526,311130,311337,311341,8749,8751
S122,321526,321526,112342,43331,113497,22723,22870
S123,317622,317622,312046,0,0,0,0
S201,317622,317622,270743,0,0,0,0
S202,317622,317622,269369,0,0,0,0
S203,317622,317622,265598,0,0,0,0
S204,317622,317622,270275,0,0,0,0
S205,317622,317622,244189,0,0,0,0
S207,317622,317622,269030,0,0,0,0
S208,317622,317622,270732,0,0,0,0
S209,317622,317622,267623,0,0,0,0
S210,317622,317622,266653,0,0,0,0
S211,317622,317622,268595,0,0,0,0
S212,317622,317622,269917,0,0,0,0
S213,317622,317622,269699,0,0,0,0
S214,317622,317622,267166,0,0,0,0
S215,317622,317622,315751,0,0,0,0
S216,317622,317622,268964,0,0,0,0
S217,317622,317622,270218,0,0,0,0
S218,317622,317622,270637,0,0,0,0
S219,317622,317622,270362,0,0,0,0
S220,317622,317622,270738,0,0,0,0
S221,317622,317622,270737,0,0,0,0
S222,317622,317622,270743,0,0,0,0
S223,317622,317622,270589,0,0,0,0
S224,317622,317622,269195,0,0,0,0
S226,317622,317622,268921,0,0,0,0
S227,317622,317622,269810,0,0,0,0
S228,317622,317622,268405,0,0,0,0
S229,317622,317622,270463,0,0,0,0
S230,317622,317622,269597,0,0,0,0
S24,321526,321526,310864,312317,312317,63026,63310
S29,317622,317622,76347,0,0,0,0
S33,317622,317622,313917,0,0,0,0
S35,317622,317622,290415,0,0,0,0
S36,317622,317622,75110,0,0,0,0
S40,317622,317622,314794,0,0,0,0
S43,321526,321526,316560,311420,316402,61207,61379
S44,321526,321526,316161,315565,315564,62340,62675
S46,317622,317622,90417,0,0,0,0
S50,321526,321526,314490,315133,307128,53646,53843
S60,321526,321526,127136,127852,127744,52222,52398
S61,317622,317622,143188,0,0,0,0
S64,317622,317622,52746,0,0,0,0
S66,317622,317622,312818,0,0,0,0
S69,317622,317622,308787,0,0,0,0
S71,317622,317622,315462,0,0,0,0
S77,317622,317622,316858,0,0,0,0
S78,317622,317622,317323,0,0,0,0
S79,317622,317622,315566,0,0,0,0
S81,317622,317622,317524,0,0,0,0
S82,317622,317622,287399,0,0,0,0
S84,317622,317622,309045,0,0,0,0
S88,317622,317622,317478,0,0,0,0
S89,317622,317622,317505,0,0,0,0
S90,317622,317622,316600,0,0,0,0
S900,317622,317622,315454,0,0,0,0
S91,317622,317622,117300,0,0,0,0
S92,317622,317622,97789,0,0,0,0
S94,317622,317622,317507,0,0,0,0

#### Dropping rows with no rain-fall reading at the particular timestamp

In [6]:
rain_data.dropna(axis=0,subset=["value"],inplace=True)
rain_data.groupby("station").count()

,date,time,value,humidity,temperature,wind_direction,wind_speed
station,,,,,,,
S07,96902,96902,96902,0,0,0,0
S08,316489,316489,316489,0,0,0,0
S100,313207,313207,313207,310703,310671,61348,61497
S102,30235,30235,30235,26125,28284,1067,1077
S104,306651,306651,306651,303393,303391,56892,57156
S105,2126,2126,2126,0,0,0,0
S106,298500,298500,298500,291108,291111,53486,53609
S107,313432,313432,313432,311185,311159,58772,59469
S108,296736,296736,296736,255660,293737,54825,55263
S109,303390,303390,303390,280621,301068,57216,57421
S11,186061,186061,186061,0,0,0,0
S111,309728,309728,309728,306309,306309,7437,7498
S112,309035,309035,309035,0,0,0,0
S113,317404,317404,317404,0,0,0,0
S114,310540,310540,310540,0,0,0,0
S115,306772,306772,306772,301912,301920,58923,59059
S116,307217,307217,307217,295242,303425,57059,57317
S117,99506,99506,99506,94815,98569,12309,12342
S118,312936,312936,312936,0,0,0,0
S119,307880,307880,307880,0,0,0,0
S120,316247,316247,316247,0,0,0,0
S121,311130,311130,311130,308716,308720,8418,8420
S122,112342,112342,112342,43307,110889,6237,6277
S123,312046,312046,312046,0,0,0,0
S201,270743,270743,270743,0,0,0,0
S202,269369,269369,269369,0,0,0,0
S203,265598,265598,265598,0,0,0,0
S204,270275,270275,270275,0,0,0,0
S205,244189,244189,244189,0,0,0,0
S207,269030,269030,269030,0,0,0,0
S208,270732,270732,270732,0,0,0,0
S209,267623,267623,267623,0,0,0,0
S210,266653,266653,266653,0,0,0,0
S211,268595,268595,268595,0,0,0,0
S212,269917,269917,269917,0,0,0,0
S213,269699,269699,269699,0,0,0,0
S214,267166,267166,267166,0,0,0,0
S215,315751,315751,315751,0,0,0,0
S216,268964,268964,268964,0,0,0,0
S217,270218,270218,270218,0,0,0,0
S218,270637,270637,270637,0,0,0,0
S219,270362,270362,270362,0,0,0,0
S220,270738,270738,270738,0,0,0,0
S221,270737,270737,270737,0,0,0,0
S222,270743,270743,270743,0,0,0,0
S223,270589,270589,270589,0,0,0,0
S224,269195,269195,269195,0,0,0,0
S226,268921,268921,268921,0,0,0,0
S227,269810,269810,269810,0,0,0,0
S228,268405,268405,268405,0,0,0,0
S229,270463,270463,270463,0,0,0,0
S230,269597,269597,269597,0,0,0,0
S24,310864,310864,310864,309713,309713,59962,60239
S29,76347,76347,76347,0,0,0,0
S33,313917,313917,313917,0,0,0,0
S35,290415,290415,290415,0,0,0,0
S36,75110,75110,75110,0,0,0,0
S40,314794,314794,314794,0,0,0,0
S43,316560,316560,316560,308834,313792,60825,60995
S44,316161,316161,316161,312944,312943,61614,61945
S46,90417,90417,90417,0,0,0,0
S50,314490,314490,314490,312530,304525,53257,53454
S60,127136,127136,127136,125779,125671,19831,19893
S61,143188,143188,143188,0,0,0,0
S64,52746,52746,52746,0,0,0,0
S66,312818,312818,312818,0,0,0,0
S69,308787,308787,308787,0,0,0,0
S71,315462,315462,315462,0,0,0,0
S77,316858,316858,316858,0,0,0,0
S78,317323,317323,317323,0,0,0,0
S79,315566,315566,315566,0,0,0,0
S81,317524,317524,317524,0,0,0,0
S82,287399,287399,287399,0,0,0,0
S84,309045,309045,309045,0,0,0,0
S88,317478,317478,317478,0,0,0,0
S89,317505,317505,317505,0,0,0,0
S90,316600,316600,316600,0,0,0,0
S900,315454,315454,315454,0,0,0,0
S91,117300,117300,117300,0,0,0,0
S92,97789,97789,97789,0,0,0,0
S94,317507,317507,317507,0,0,0,0

## Covariance and Correlation of different columns

#### Including the rows without humidity, temperature, windspeed, wind direction

In [7]:
cov_matrix = pd.DataFrame.cov(rain_data)
print(cov_matrix)

C:\Users\Edward\AppData\Local\Temp\ipykernel_11212\2650704498.py:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  cov_matrix = pd.DataFrame.cov(rain_data)

                   value    humidity  temperature  wind_direction  wind_speed
value           0.086185    0.337633    -0.080860        0.626785   -0.000576
humidity        0.337633  133.938702   -20.483001       20.823417   -0.345789
temperature    -0.080860  -20.483001     4.685994        0.721350    0.278603
wind_direction  0.626785   20.823417     0.721350    13346.512069  -48.862658
wind_speed     -0.000576   -0.345789     0.278603      -48.862658    8.605431

In [8]:
corr_matrix = rain_data.corr()
print(corr_matrix)

C:\Users\Edward\AppData\Local\Temp\ipykernel_11212\1338822609.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = rain_data.corr()

                   value  humidity  temperature  wind_direction  wind_speed
value           1.000000  0.109749    -0.133924        0.011120   -0.000401
humidity        0.109749  1.000000    -0.819775        0.017548   -0.011448
temperature    -0.133924 -0.819775     1.000000        0.003014    0.045875
wind_direction  0.011120  0.017548     0.003014        1.000000   -0.144276
wind_speed     -0.000401 -0.011448     0.045875       -0.144276    1.000000

#### Excluding the rows without humidity, temperature, windspeed, wind direction

In [9]:
stations_with_humidity = rain_data
stations_with_humidity.dropna(axis=0,how="any",inplace=True)

In [10]:
cov_matrix = pd.DataFrame.cov(stations_with_humidity)
print(cov_matrix)

                   value    humidity  temperature  wind_direction  wind_speed
value           0.215236    0.711270    -0.174531        0.461502   -0.005399
humidity        0.711270  105.235047   -17.336823       20.257653   -0.332593
temperature    -0.174531  -17.336823     4.310037        1.776926    0.312627
wind_direction  0.461502   20.257653     1.776926    13373.064016  -50.767260
wind_speed     -0.005399   -0.332593     0.312627      -50.767260    8.649832

C:\Users\Edward\AppData\Local\Temp\ipykernel_11212\3243203892.py:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  cov_matrix = pd.DataFrame.cov(stations_with_humidity)

In [11]:
corr_matrix = stations_with_humidity.corr()
print(corr_matrix)

                   value  humidity  temperature  wind_direction  wind_speed
value           1.000000  0.149450    -0.181207        0.008602   -0.003957
humidity        0.149450  1.000000    -0.814046        0.017076   -0.011024
temperature    -0.181207 -0.814046     1.000000        0.007401    0.051202
wind_direction  0.008602  0.017076     0.007401        1.000000   -0.149267
wind_speed     -0.003957 -0.011024     0.051202       -0.149267    1.000000

C:\Users\Edward\AppData\Local\Temp\ipykernel_11212\1703577285.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = stations_with_humidity.corr()